name: PR Event Workflow
on:
  pull_request:
    types: [opened, reopened, edited, closed, synchronize, assigned, unassigned, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]
  issue_comment:
    types: [created, edited, deleted]
jobs:
  call-update-spreadsheet:
    uses: learningequality/.github/.github/workflows/update-pr-spreadsheet.yml@main
    with:
      pr_data: |
        {
          "merged_at": "${{ github.event.pull_request.merged_at }}",
          "html_url": "${{ github.event.pull_request.html_url }}",
          "user_login": "${{ github.event.pull_request.user.login }}",
          "title": "${{ github.event.pull_request.title }}",
          "repo_name": "${{ github.event.pull_request.base.repo.name }}",
          "updated_at": "${{ github.event.pull_request.updated_at }}",
          "requested_reviewers": "${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}",
          "assignees": "${{ join(github.event.pull_request.assignees.*.login, ',') }}",
          "user_site_admin": ${{ github.event.pull_request.user.site_admin }},
          "user_type": "${{ github.event.pull_request.user.type }}",
          "author_association": "${{ github.event.pull_request.author_association }}",
          "state": "${{ github.event.pull_request.state }}"
        }
    secrets:
      CONTRIBUTIONS_SPREADSHEET_ID: ${{ secrets.CONTRIBUTIONS_SPREADSHEET_ID }}
      CONTRIBUTIONS_SHEET_NAME: ${{ secrets.CONTRIBUTIONS_SHEET_NAME }}
      GH_UPLOADER_GCP_SA_CREDENTIALS: ${{ secrets.GH_UPLOADER_GCP_SA_CREDENTIALS }}
